# Generated by Django 6.0.1 on 2026-01-29 01:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TitikIrigasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lokasi', models.CharField(max_length=100)),
                ('keterangan', models.TextField()),
                ('koordinat', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('foto', models.ImageField(upload_to='foto_irigasi/')),
                ('waktu_input', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
