# Generated by Django 6.0.1 on 2026-01-29 02:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaerahIrigasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_di', models.CharField(max_length=50, unique=True)),
                ('nama_di', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('luas_fungsional', models.FloatField(help_text='Luas dalam Hektar (Ha)')),
                ('koordinat', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('status_kondisi', models.CharField(default='Baik', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Daerah Irigasi',
            },
        ),
    ]
