# Generated by Django 6.0.1 on 2026-01-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_daerahirigasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daerahirigasi',
            options={},
        ),
        migrations.RemoveField(
            model_name='daerahirigasi',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='daerahirigasi',
            name='status_kondisi',
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='kewenangan',
            field=models.CharField(default='Kabupaten', max_length=100),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='kondisi_baik',
            field=models.FloatField(default=0, help_text='Panjang kondisi baik (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='kondisi_rusak_berat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='kondisi_rusak_ringan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='panjang_saluran',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='tingkat_jaringan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='luas_fungsional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='nama_di',
            field=models.CharField(max_length=200),
        ),
    ]
