# Generated by Django 6.0.1 on 2026-01-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_daerahirigasi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
