# Generated by Django 6.0.1 on 2026-01-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_daerahirigasi_latitude_daerahirigasi_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerPendukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('jalan', 'Jalan'), ('wilayah', 'Batas Wilayah'), ('air', 'Sumber Air/Waduk')], max_length=50)),
                ('file_geojson', models.FileField(upload_to='geojson/')),
                ('warna_garis', models.CharField(default='#3388ff', help_text='Kode HEX warna', max_length=7)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
