# Generated by Django 6.0.1 on 2026-01-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_layerpendukung_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='file_geojson',
            field=models.FileField(blank=True, help_text='Upload file .json atau .geojson untuk DI ini', null=True, upload_to='geojson/di/'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='kategori_map',
            field=models.CharField(choices=[('irigasi', 'Saluran'), ('lahan', 'Luasan Areal'), ('bangunan', 'Bangunan/Bendung')], default='lahan', max_length=50),
        ),
    ]
