# Generated by Django 6.0.1 on 2026-01-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_alter_daerahirigasi_kondisi_baik'),
    ]

    operations = [
        migrations.AddField(
            model_name='titikirigasi',
            name='kondisi_umum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='titikirigasi',
            name='surveyor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
