# Generated by Django 6.0.1 on 2026-02-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_titikirigasi_kondisi_umum_titikirigasi_surveyor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daerahirigasi',
            options={'verbose_name_plural': 'Daerah Irigasi'},
        ),
        migrations.RemoveField(
            model_name='daerahirigasi',
            name='kategori_map',
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='bendung',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='sumber_air',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='wilayah_upt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='kewenangan',
            field=models.CharField(default='Pem. Kab. Cirebon', max_length=100),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='kode_di',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='luas_fungsional',
            field=models.FloatField(default=0, help_text='Areal Fungsional (Ha)'),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='panjang_saluran',
            field=models.FloatField(default=0, help_text='Total Panjang Saluran (m)'),
        ),
    ]
