# Generated by Django 6.0.1 on 2026-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_alter_daerahirigasi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='luas_permen',
            field=models.FloatField(default=0, help_text='Areal Permen PU No. 14 Th 2015 (Ha)'),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='kode_di',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='luas_fungsional',
            field=models.FloatField(default=0, help_text='Areal Fungsional Saat Ini (Ha)'),
        ),
    ]
