# Generated by Django 6.0.1 on 2026-02-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_daerahirigasi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saluran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_saluran', models.CharField(max_length=255)),
                ('nomenklatur', models.CharField(max_length=100)),
                ('bangunan_hulu', models.CharField(max_length=100)),
                ('bangunan_hilir', models.CharField(max_length=100)),
                ('kode_saluran', models.CharField(max_length=100)),
                ('panjang_saluran', models.FloatField(default=0)),
                ('luas_layanan', models.FloatField(default=0)),
                ('kondisi_aset', models.CharField(choices=[('BAIK', 'BAIK'), ('SEDANG', 'SEDANG'), ('JELEK', 'JELEK')], max_length=20)),
                ('nilai_persen', models.FloatField(default=0)),
                ('daerah_irigasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saluran_aset', to='apps.daerahirigasi')),
            ],
        ),
        migrations.CreateModel(
            name='Bangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bangunan', models.CharField(max_length=255)),
                ('nomenklatur', models.CharField(max_length=100)),
                ('kode_aset', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('tgl_survey', models.DateField(blank=True, null=True)),
                ('tim_survey', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_aset', models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/')),
                ('luas_layanan_ha', models.FloatField(default=0)),
                ('fungsi_bangunan_sipil', models.CharField(blank=True, max_length=255, null=True)),
                ('fungsi_bangunan_me', models.CharField(blank=True, max_length=255, null=True)),
                ('prioritas', models.IntegerField(default=0)),
                ('kondisi_aset', models.CharField(max_length=50)),
                ('nilai_persen', models.FloatField(default=0)),
                ('daerah_irigasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bangunan_aset', to='apps.daerahirigasi')),
                ('saluran', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_bangunan', to='apps.saluran')),
            ],
        ),
    ]
