# Generated by Django 6.0.1 on 2026-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_saluran_bangunan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saluran',
            options={'verbose_name_plural': 'Aset Saluran'},
        ),
        migrations.AddField(
            model_name='saluran',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='saluran/foto/'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='fungsi_bangunan_sipil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saluran',
            name='fungsi_jalan_inspeksi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saluran',
            name='jumlah_lining',
            field=models.IntegerField(default=1, help_text='Jumlah lining saluran'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='prioritas',
            field=models.IntegerField(default=1, help_text='Urutan prioritas (misal: 1, 2, 3)'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='bangunan_hilir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='bangunan_hulu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='kode_saluran',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='luas_layanan',
            field=models.FloatField(default=0, help_text='Dalam Hektar (Ha)'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='nilai_persen',
            field=models.FloatField(default=0, help_text='Nilai kondisi dalam persen (%)'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='nomenklatur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='panjang_saluran',
            field=models.FloatField(default=0, help_text='Dalam meter'),
        ),
    ]
