# Generated by Django 6.0.1 on 2026-02-05 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_saluran_options_saluran_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsetSaluran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aset_saluran', models.CharField(max_length=255)),
                ('nomenklatur', models.CharField(blank=True, max_length=100, null=True)),
                ('bangunan_hulu', models.CharField(blank=True, max_length=100, null=True)),
                ('bangunan_hilir', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_saluran', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_aset/saluran/')),
                ('jumlah_lining', models.IntegerField(default=0)),
                ('panjang_saluran_m', models.FloatField(default=0, help_text='Panjang dalam meter')),
                ('luas_layanan_ha', models.FloatField(default=0, help_text='Luas dalam hektar')),
                ('fungsi_bangunan_sipil', models.CharField(blank=True, max_length=255, null=True)),
                ('fungsi_jalan_inspeksi', models.CharField(blank=True, max_length=255, null=True)),
                ('prioritas', models.FloatField(default=0)),
                ('kondisi_aset', models.CharField(max_length=50)),
                ('nilai_persen', models.FloatField(default=0)),
                ('saluran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aset_fisik_saluran', to='apps.saluran')),
            ],
            options={
                'verbose_name_plural': 'Aset Saluran',
            },
        ),
    ]
