# Generated by Django 6.0.1 on 2026-02-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_saluran_options_rename_kode_aset_bangunan_desa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saluran',
            name='tingkat_jaringan',
            field=models.CharField(choices=[('Teknis', 'Teknis')], default='Teknis', max_length=50),
        ),
    ]
