# Generated by Django 6.0.1 on 2026-02-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_alter_saluran_tingkat_jaringan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangunan',
            old_name='jumlah_pintu',
            new_name='pintu_total_unit',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='jenis_pintu',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='kondisi_pintu',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='kondisi_sal_induk',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='kondisi_sal_sekunder',
        ),
        migrations.AddField(
            model_name='bangunan',
            name='pintu_baik',
            field=models.IntegerField(default=0, verbose_name='Pintu Kondisi Baik'),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='pintu_jenis',
            field=models.CharField(choices=[('Sorong', 'Sorong'), ('Romijn', 'Romijn'), ('Cipoletti', 'Cipoletti'), ('Crump-de-Gruyter', 'Crump-de-Gruyter')], default='Sorong', max_length=50),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='pintu_rusak_berat',
            field=models.IntegerField(default=0, verbose_name='Pintu Rusak Berat'),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='pintu_rusak_ringan',
            field=models.IntegerField(default=0, verbose_name='Pintu Rusak Ringan'),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_induk_baik',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_induk_bap',
            field=models.FloatField(default=0, verbose_name='Belum Ada Pasangan (BAP)'),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_induk_rusak_berat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_induk_rusak_ringan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_sekunder_baik',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_sekunder_bap',
            field=models.FloatField(default=0, verbose_name='Belum Ada Pasangan (BAP)'),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_sekunder_rusak_berat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bangunan',
            name='sal_sekunder_rusak_ringan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='bangunan_hilir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='bangunan_hulu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='desa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Desa'),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kecamatan'),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='luas_areal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='nomenklatur_pengatur',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='panjang_saluran_antar_ruas',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='tersier_terlayani',
            field=models.CharField(max_length=255),
        ),
    ]
