# Generated by Django 6.0.1 on 2026-02-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_daerahirigasi_total_luas_fungsional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangunan',
            name='desa',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='keterangan',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='luas_areal',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='nomenklatur_pengatur',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='pintu_baik',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='pintu_jenis',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='pintu_rusak_berat',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='pintu_rusak_ringan',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='pintu_total_unit',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_induk_baik',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_induk_bap',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_induk_rusak_berat',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_induk_rusak_ringan',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_sekunder_baik',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_sekunder_bap',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_sekunder_rusak_berat',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='sal_sekunder_rusak_ringan',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='tersier_terlayani',
        ),
        migrations.AddField(
            model_name='bangunan',
            name='nomenklatur',
            field=models.CharField(default=0, max_length=100, verbose_name='Nomenklatur Ruas Bangunan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='bangunan_hilir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hilir_dari', to='apps.bangunan'),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='bangunan_hulu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hulu_dari', to='apps.bangunan'),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='kode_di',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='nama_di',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='areal_fungsional',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='panjang_saluran',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DetailLayananBangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('desa', models.CharField(blank=True, max_length=100, null=True)),
                ('tersier_terlayani', models.CharField(blank=True, max_length=255, null=True)),
                ('luas_areal', models.FloatField(default=0, verbose_name='Luas Areal (Ha)')),
                ('pintu_jenis', models.CharField(choices=[('Sorong', 'Sorong'), ('Romijn', 'Romijn'), ('Cipoletti', 'Cipoletti')], default='Sorong', max_length=50)),
                ('pintu_total_unit', models.IntegerField(default=0)),
                ('pintu_baik', models.IntegerField(default=0)),
                ('pintu_rusak_ringan', models.IntegerField(default=0)),
                ('pintu_rusak_berat', models.IntegerField(default=0)),
                ('sal_induk_baik', models.FloatField(default=0)),
                ('sal_induk_rusak_ringan', models.FloatField(default=0)),
                ('sal_induk_rusak_berat', models.FloatField(default=0)),
                ('sal_induk_bap', models.FloatField(default=0)),
                ('sal_sekunder_baik', models.FloatField(default=0)),
                ('sal_sekunder_rusak_ringan', models.FloatField(default=0)),
                ('sal_sekunder_rusak_berat', models.FloatField(default=0)),
                ('sal_sekunder_bap', models.FloatField(default=0)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('bangunan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layanan_list', to='apps.bangunan')),
            ],
        ),
    ]
