# Generated by Django 6.0.1 on 2026-02-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_remove_bangunan_desa_remove_bangunan_kecamatan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bangunan',
            old_name='nomenklatur',
            new_name='nomenklatur_ruas',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='bangunan_hilir',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='bangunan_hulu',
        ),
        migrations.RemoveField(
            model_name='bangunan',
            name='nama_bangunan',
        ),
        migrations.AddField(
            model_name='bangunan',
            name='terhubung_ke',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruas_berikutnya', to='apps.bangunan', verbose_name='Terhubung ke Ruas (Hulu)'),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='panjang_saluran_antar_ruas',
            field=models.FloatField(default=0, verbose_name='Panjang Ruas (m)'),
        ),
    ]
