# Generated by Django 6.0.1 on 2026-02-11 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_rename_nomenklatur_bangunan_nomenklatur_ruas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bangunan',
            name='tipe_ruas',
        ),
        migrations.RemoveField(
            model_name='detaillayananbangunan',
            name='bangunan',
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='nomenklatur_pengatur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='layanan_list', to='apps.bangunan', verbose_name='Nomenklatur Bangunan Pengatur'),
            preserve_default=False,
        ),
    ]
