# Generated by Django 6.0.1 on 2026-02-11 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_remove_bangunan_tipe_ruas_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detaillayananbangunan',
            options={'verbose_name': 'Data Teknis & Layanan', 'verbose_name_plural': 'DAFTAR NOMENKLATUR BANGUNAN PENGATUR'},
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='bangunan',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='layanan_list', to='apps.bangunan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='nomenklatur_pengatur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='NOMENKLATUR BANGUNAN PENGATUR'),
        ),
    ]
