# Generated by Django 6.0.1 on 2026-02-11 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0027_alter_detaillayananbangunan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan',
            name='daerah_irigasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bangunan_langsung', to='apps.daerahirigasi', verbose_name='Daerah Irigasi (Pilih jika Bangunan Utama)'),
        ),
        migrations.AlterField(
            model_name='bangunan',
            name='saluran',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bangunan_list', to='apps.saluran', verbose_name='Saluran Irigasi (Pilih jika Bangunan Ruas)'),
        ),
    ]
