# Generated by Django 6.0.1 on 2026-02-11 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0028_bangunan_daerah_irigasi_alter_bangunan_saluran'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelaporanAset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(default=2024)),
                ('luas_fungsional', models.FloatField(default=0)),
                ('utama_prasarana_fisik', models.FloatField(default=0, verbose_name='Prasarana Fisik (Utama)')),
                ('utama_produktivitas_tanam', models.FloatField(default=0, verbose_name='Produktivitas Tanam (Utama)')),
                ('utama_sarana_penunjang', models.FloatField(default=0, verbose_name='Sarana Penunjang (Utama)')),
                ('utama_organisasi_personalia', models.FloatField(default=0, verbose_name='Organisasi Personalia (Utama)')),
                ('utama_dokumentasi', models.FloatField(default=0, verbose_name='Dokumentasi (Utama)')),
                ('utama_gp3a_ip3a', models.FloatField(default=0, verbose_name='GP3A / IP3A')),
                ('tersier_prasarana_fisik', models.FloatField(default=0, verbose_name='Prasarana Fisik (Tersier)')),
                ('tersier_produktivitas_tanam', models.FloatField(default=0, verbose_name='Produktivitas Tanam (Tersier)')),
                ('tersier_kondisi_op', models.FloatField(default=0, verbose_name='Kondisi OP')),
                ('tersier_petugas_pembagi_air', models.FloatField(default=0, verbose_name='Petugas Pembagi Air')),
                ('tersier_dokumentasi', models.FloatField(default=0, verbose_name='Dokumentasi (Tersier)')),
                ('tersier_p3a', models.FloatField(default=0, verbose_name='P3A')),
                ('daerah_irigasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_aksi', to='apps.daerahirigasi')),
            ],
            options={
                'verbose_name': 'Pelaporan Aset & IKSI',
                'verbose_name_plural': 'PELAPORAN ASET & IKSI',
            },
        ),
    ]
