# Generated by Django 6.0.1 on 2026-02-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_pelaporanaset'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPintu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Master Jenis Pintu',
                'verbose_name_plural': 'Master Jenis Pintu',
            },
        ),
    ]
