# Generated by Django 6.0.1 on 2026-02-11 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_alter_jenispintu_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanIksiSaluran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(default=2024)),
                ('surveyor', models.CharField(blank=True, max_length=100)),
                ('total_nilai_iksi', models.FloatField(default=0, verbose_name='Total Nilai IKSI (%)')),
                ('catatan_rekomendasi', models.TextField(blank=True)),
                ('saluran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_iksi', to='apps.saluran')),
            ],
            options={
                'verbose_name': 'IKSI - 1. Rangkuman',
                'verbose_name_plural': 'IKSI - 1. Rangkuman',
            },
        ),
        migrations.CreateModel(
            name='RuasIksiSaluran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_item', models.CharField(help_text='Contoh: S02_01', max_length=20)),
                ('nama_ruas_item', models.CharField(max_length=255, verbose_name='Uraian Ruas/Kuesioner')),
                ('nilai_kondisi', models.FloatField(default=0)),
                ('bobot_pengaruh', models.FloatField(default=0)),
                ('nilai_akhir', models.FloatField(default=0)),
                ('foto_kondisi', models.ImageField(blank=True, null=True, upload_to='iksi/saluran/')),
                ('catatan_ruas', models.TextField(blank=True, null=True)),
                ('laporan_utama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruas_detail', to='apps.laporaniksisaluran')),
            ],
            options={
                'verbose_name': 'IKSI - 2. Detail Ruas',
                'verbose_name_plural': 'IKSI - 2. Detail Ruas',
            },
        ),
    ]
