# Generated by Django 6.0.1 on 2026-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_laporaniksisaluran_ruasiksisaluran'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='luas_baku_onemap',
            field=models.FloatField(default=0, verbose_name='Luas Baku OneMap (Ha)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='luas_baku_permen',
            field=models.FloatField(default=0, verbose_name='Luas Baku Permen PU No. 14/2015 (Ha)'),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='total_luas_fungsional',
            field=models.FloatField(default=0, verbose_name='Total Luas Fungsional (Ha)'),
        ),
        migrations.AlterField(
            model_name='daerahirigasi',
            name='total_panjang_jaringan',
            field=models.FloatField(default=0, verbose_name='Total Panjang Jaringan (m)'),
        ),
    ]
