# Generated by Django 6.0.1 on 2026-02-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_daerahirigasi_luas_baku_onemap_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detaillayananbangunan',
            options={'verbose_name': 'Detail Ruas & Layanan', 'verbose_name_plural': 'DAFTAR NOMENKLATUR BANGUNAN PENGATUR'},
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='pintu_total_unit',
            field=models.IntegerField(default=0, verbose_name='Pintu Total Unit'),
        ),
    ]
