# Generated by Django 6.0.1 on 2026-02-11 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_alter_detaillayananbangunan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiBangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_aset_kode', models.CharField(max_length=10)),
                ('nama_bangunan', models.CharField(max_length=100)),
                ('nomenklatur', models.CharField(max_length=100)),
                ('tahun_dibangun', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pai/bangunan/')),
                ('catatan', models.TextField(blank=True)),
                ('bangunan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pai_bangunan', to='apps.bangunan')),
            ],
            options={
                'verbose_name': 'PAI Bangunan',
                'verbose_name_plural': 'PAI Bangunan',
            },
        ),
        migrations.CreateModel(
            name='Paisaluran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_aset_kode', models.CharField(max_length=10, verbose_name='Jenis Aset (Kode)')),
                ('nama_aset', models.CharField(max_length=100)),
                ('nomenklatur', models.CharField(max_length=100)),
                ('bangunan_hulu', models.CharField(max_length=100)),
                ('bangunan_hilir', models.CharField(max_length=100)),
                ('subsistem', models.CharField(blank=True, max_length=100)),
                ('luas_layanan_ha', models.FloatField(default=0)),
                ('q_desain', models.FloatField(default=0, verbose_name='Q Desain (m3/det)')),
                ('panjang_saluran_m', models.FloatField(default=0)),
                ('tahun_dibangun', models.IntegerField(blank=True, null=True)),
                ('pintu_jumlah', models.IntegerField(default=0)),
                ('pintu_lebar_m', models.FloatField(default=0)),
                ('pintu_tinggi_m', models.FloatField(default=0)),
                ('pintu_tenaga', models.CharField(choices=[('MANUAL', 'Manual'), ('LISTRIK', 'Listrik')], default='MANUAL', max_length=50)),
                ('pintu_bahan', models.CharField(default='Besi', max_length=50)),
                ('desain_li', models.FloatField(default=0, verbose_name='Desain Li (m)')),
                ('desain_b', models.FloatField(default=0, verbose_name='Desain b (m)')),
                ('desain_la', models.FloatField(default=0, verbose_name='Desain La (m)')),
                ('desain_h', models.FloatField(default=0, verbose_name='Desain H (m)')),
                ('desain_kemiringan', models.CharField(default='90 derajat', max_length=20)),
                ('nyata_li', models.FloatField(default=0, verbose_name='Kenyataan Li (m)')),
                ('nyata_b', models.FloatField(default=0, verbose_name='Kenyataan b (m)')),
                ('nyata_la', models.FloatField(default=0, verbose_name='Kenyataan La (m)')),
                ('nyata_h', models.FloatField(default=0, verbose_name='Kenyataan H (m)')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pai/saluran/')),
                ('catatan', models.TextField(blank=True)),
                ('saluran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pai_saluran', to='apps.saluran')),
            ],
            options={
                'verbose_name': 'PAI Saluran',
                'verbose_name_plural': 'PAI Saluran',
            },
        ),
    ]
