# Generated by Django 6.0.1 on 2026-02-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_paibangunan_paisaluran'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asetsaluran',
            options={'verbose_name_plural': 'ASET SALURAN'},
        ),
        migrations.AlterModelOptions(
            name='bangunan',
            options={'verbose_name': 'Data Aset Bangunan', 'verbose_name_plural': '3. DATA ASET BANGUNAN'},
        ),
        migrations.AlterModelOptions(
            name='daerahirigasi',
            options={'verbose_name': 'Data Daerah Irigasi', 'verbose_name_plural': '1. DATA DAERAH IRIGASI'},
        ),
        migrations.AlterModelOptions(
            name='laporaniksisaluran',
            options={'verbose_name': 'IKSI - 1. Rangkuman', 'verbose_name_plural': '4. DATA IKSI(Rangkuman)'},
        ),
        migrations.AlterModelOptions(
            name='pelaporanaset',
            options={'verbose_name': 'Pelaporan Aset & IKSI', 'verbose_name_plural': '5. PELAPORAN ASET & IKSI'},
        ),
        migrations.AlterModelOptions(
            name='saluran',
            options={'verbose_name': 'Data Saluran', 'verbose_name_plural': '2. DATA SALURAN'},
        ),
        migrations.RemoveField(
            model_name='detaillayananbangunan',
            name='tersier_terlayani',
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='keterangan_aset',
            field=models.CharField(default=0, help_text='Contoh: Ciwado', max_length=255, verbose_name='Keterangan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='kode_aset',
            field=models.CharField(choices=[('B01', 'B01'), ('B02', 'B02'), ('P01', 'P01'), ('P02', 'P02'), ('P03', 'P03'), ('S01', 'S01'), ('S02', 'S02'), ('S03', 'S03'), ('S04', 'S04'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17')], default=0, max_length=5, verbose_name='Jenis Aset (Kode)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='nama_aset_manual',
            field=models.CharField(default=0, help_text='Contoh: Saluran Primer', max_length=150, verbose_name='Nama Aset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paisaluran',
            name='jenis_aset_kode',
            field=models.CharField(choices=[('S01', 'S01 - Saluran Primer'), ('S02', 'S02 - Saluran Sekunder'), ('S03', 'S03 - Saluran Suplesi'), ('S04', 'S04 - Saluran Muka'), ('S11', 'S11 - Saluran Pembuang'), ('S12', 'S12 - Saluran Gendong'), ('S13', 'S13 - Saluran Pengelak Banjir'), ('S15', 'S15 - Saluran Tersier'), ('S16', 'S16 - Saluran Kuarter'), ('S17', 'S17 - Saluran Pembuang (Tersier)')], max_length=5, verbose_name='Jenis Aset (Kode)'),
        ),
    ]
