# Generated by Django 6.0.1 on 2026-02-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_alter_asetsaluran_options_alter_bangunan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='jumlah_pintu',
            field=models.IntegerField(default=0, verbose_name='Total Jumlah Pintu'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='panjang_primer',
            field=models.FloatField(default=0, verbose_name='Total Panjang Primer (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='panjang_sekunder',
            field=models.FloatField(default=0, verbose_name='Total Panjang Sekunder (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='pintu_baik',
            field=models.IntegerField(default=0, verbose_name='Pintu Baik'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='pintu_rb',
            field=models.IntegerField(default=0, verbose_name='Pintu Rusak Berat'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='pintu_rr',
            field=models.IntegerField(default=0, verbose_name='Pintu Rusak Ringan'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='primer_baik',
            field=models.FloatField(default=0, verbose_name='Primer Baik (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='primer_bap',
            field=models.FloatField(default=0, verbose_name='Primer Belum Ada Pasangan (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='primer_rb',
            field=models.FloatField(default=0, verbose_name='Primer Rusak Berat (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='primer_rr',
            field=models.FloatField(default=0, verbose_name='Primer Rusak Ringan (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='sekunder_baik',
            field=models.FloatField(default=0, verbose_name='Sekunder Baik (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='sekunder_bap',
            field=models.FloatField(default=0, verbose_name='Sekunder Belum Ada Pasangan (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='sekunder_rb',
            field=models.FloatField(default=0, verbose_name='Sekunder Rusak Berat (m)'),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='sekunder_rr',
            field=models.FloatField(default=0, verbose_name='Sekunder Rusak Ringan (m)'),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='nama_aset_manual',
            field=models.CharField(max_length=150, verbose_name='Nama Aset'),
        ),
    ]
