# Generated by Django 6.0.1 on 2026-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_daerahirigasi_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='bendung',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='sumber_air',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
