# Generated by Django 6.0.1 on 2026-02-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_daerahirigasi_bendung_daerahirigasi_sumber_air'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_aset',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitude'),
        ),
    ]
