# Generated by Django 6.0.1 on 2026-02-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_detaillayananbangunan_foto_aset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='kode_aset',
            field=models.CharField(blank=True, choices=[('B01', 'B01'), ('B02', 'B02'), ('P01', 'P01'), ('P02', 'P02'), ('P03', 'P03'), ('S01', 'S01'), ('S02', 'S02'), ('S03', 'S03'), ('S04', 'S04'), ('S11', 'S11'), ('S12', 'S12'), ('S13', 'S13'), ('S15', 'S15'), ('S16', 'S16'), ('S17', 'S17')], max_length=5, null=True, verbose_name='Jenis Aset (Kode)'),
        ),
    ]
