# Generated by Django 6.0.1 on 2026-02-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_alter_saluran_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan',
            name='jenis_bangunan',
            field=models.CharField(choices=[('BENDUNG', 'Bendung'), ('POMPA', 'Pompa/Pumping'), ('BAGI', 'Bangunan Bagi'), ('SADAP', 'Bangunan Sadap'), ('BAGISADAP', 'Bangunan Bagi Sadap'), ('PELENGKAP', 'Bangunan Pelengkap')], default='PELENGKAP', max_length=20),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='kelompok_di',
            field=models.CharField(choices=[('1', 'Kelompok 1 (> 1000 ha) - Bobot Utama 80%:Tersier 20%'), ('2', 'Kelompok 2 (150 - 1000 ha) - Bobot Utama 60%:Tersier 40%'), ('3', 'Kelompok 3 (< 150 ha) - Bobot Utama 50%:Tersier 50%')], default='3', max_length=1),
        ),
        migrations.AddField(
            model_name='saluran',
            name='kinerja_individu',
            field=models.CharField(choices=[('B', 'Baik'), ('RR', 'Rusak Ringan'), ('RS', 'Rusak Sedang'), ('RB', 'Rusak Berat'), ('RT', 'Rusak Total')], default='B', max_length=2),
        ),
        migrations.CreateModel(
            name='AsetPendukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aset', models.CharField(max_length=100)),
                ('jumlah', models.IntegerField(default=1)),
                ('kondisi', models.CharField(max_length=50)),
                ('daerah_irigasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.daerahirigasi')),
            ],
        ),
    ]
