# Generated by Django 6.0.1 on 2026-02-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_bangunan_jenis_bangunan_daerahirigasi_kelompok_di_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangunan',
            name='icon_png',
            field=models.ImageField(blank=True, help_text='Upload icon PNG transparan (B01, P01, dll)', null=True, upload_to='icons_epaksi/'),
        ),
        migrations.AlterField(
            model_name='laporaniksisaluran',
            name='total_nilai_iksi',
            field=models.FloatField(default=0),
        ),
    ]
