# Generated by Django 6.0.1 on 2026-02-15 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_bangunan_icon_png_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daerahirigasi',
            name='path_koordinat',
            field=models.TextField(blank=True, help_text='Data koordinat tracking', null=True),
        ),
    ]
