# Generated by Django 6.0.1 on 2026-02-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_daerahirigasi_created_at_daerahirigasi_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saluran',
            name='kode_aset_saluran',
            field=models.CharField(choices=[('S01', 'S01 - Saluran Primer'), ('S02', 'S02 - Saluran Sekunder'), ('S03', 'S03 - Saluran Suplesi'), ('S04', 'S04 - Saluran Muka'), ('S11', 'S11 - Saluran Pembuang'), ('S12', 'S12 - Saluran Gendong'), ('S13', 'S13 - Saluran Pengelak Banjir'), ('S15', 'S15 - Saluran Tersier'), ('S16', 'S16 - Saluran Kuarter'), ('S17', 'S17 - Saluran Pembuang (Tersier)'), ('P99', 'P99 - Saluran Lain-lain')], default='S01', max_length=5),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='kode_aset',
            field=models.CharField(blank=True, choices=[('B01', 'B01 - Bendung Tetap'), ('B02', 'B02 - Bendung Gerak'), ('B03', 'B03 - Bendung Karet'), ('P01', 'P01 - Bangunan Bagi'), ('P02', 'P02 - Bangunan Sadap'), ('P03', 'P03 - Bangunan Bagi Sadap'), ('P10', 'P10 - Bangunan Terjun'), ('P21', 'P21 - Talang'), ('P22', 'P22 - Gorong-gorong')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='laporaniksisaluran',
            name='total_nilai_iksi',
            field=models.FloatField(default=0, verbose_name='Total Nilai IKSI (%)'),
        ),
        migrations.AlterField(
            model_name='paisaluran',
            name='jenis_aset_kode',
            field=models.CharField(choices=[('S01', 'S01 - Saluran Primer'), ('S02', 'S02 - Saluran Sekunder'), ('S03', 'S03 - Saluran Suplesi'), ('S04', 'S04 - Saluran Muka'), ('S11', 'S11 - Saluran Pembuang'), ('S12', 'S12 - Saluran Gendong'), ('S13', 'S13 - Saluran Pengelak Banjir'), ('S15', 'S15 - Saluran Tersier'), ('S16', 'S16 - Saluran Kuarter'), ('S17', 'S17 - Saluran Pembuang (Tersier)'), ('P99', 'P99 - Saluran Lain-lain')], max_length=5, verbose_name='Jenis Aset (Kode)'),
        ),
    ]
