# Generated by Django 6.0.1 on 2026-02-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0049_saluran_kode_aset_saluran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saluran',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='kode_aset',
            field=models.CharField(blank=True, choices=[('B01', 'B01 - Bendung'), ('B02', 'B02 - Bendung Gerak'), ('B03', 'B03 - Pengambilan Bebas'), ('B04', 'B04 - Pompa Hidrolik'), ('B06', 'B06 - Bendungan'), ('B07', 'B07 - Pompa Elektrik'), ('B99', 'B99 - Pangkal Saluran (Tanpa Bangunan)'), ('C01', 'C01 - Pengukur Debit'), ('C02', 'C02 - Siphon'), ('C03', 'C03 - Gorong-gorong'), ('C04', 'C04 - Talang'), ('C05', 'C05 - Kantong Lumpur'), ('C06', 'C06 - Jembatan'), ('C07', 'C07 - Terjunan'), ('C08', 'C08 - Pelimpah Samping'), ('C09', 'C09 - Tempat Cuci'), ('C10', 'C10 - Tempat Mandi Hewan'), ('C11', 'C11 - Got Miring'), ('C12', 'C12 - Gorong-gorong Silang'), ('C13', 'C13 - Pelimpah Corong'), ('C14', 'C14 - Pintu Pembuang'), ('C15', 'C15 - Oncoran'), ('C16', 'C16 - Bangunan Inlet'), ('C17', 'C17 - Terowongan'), ('C18', 'C18 - Cross Drain'), ('C19', 'C19 - Pintu Klep'), ('C20', 'C20 - Outlet'), ('C21', 'C21 - Krib'), ('C22', 'C22 - Tanggul'), ('P01', 'P01 - Bagi'), ('P02', 'P02 - Bagi Sadap'), ('P03', 'P03 - Sadap'), ('P04', 'P04 - Sadap Langsung'), ('P11', 'P11 - Bangunan Pertemuan'), ('P21', 'P21 - Box Tersier'), ('P22', 'P22 - Box Kuarter'), ('P99', 'P99 - Ujung Saluran (Tanpa Bangunan)')], max_length=5, null=True),
        ),
    ]
