# Generated by Django 6.0.1 on 2026-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0050_saluran_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saluran',
            name='keterangan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saluran',
            name='kondisi_aset',
            field=models.CharField(default='BAIK', max_length=50),
        ),
        migrations.AddField(
            model_name='saluran',
            name='path_koordinat',
            field=models.TextField(blank=True, null=True, verbose_name='Titik Koordinat Tracking'),
        ),
    ]
