# Generated by Django 6.0.1 on 2026-02-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0051_saluran_keterangan_saluran_kondisi_aset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saluran',
            name='panjang_baik',
            field=models.FloatField(default=0, help_text='Total panjang kondisi Baik (m)'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='panjang_rb',
            field=models.FloatField(default=0, help_text='Total panjang kondisi Rusak Berat (m)'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='panjang_rr',
            field=models.FloatField(default=0, help_text='Total panjang kondisi Rusak Ringan (m)'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='path_kondisi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
