# Generated by Django 6.0.1 on 2026-02-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0052_saluran_panjang_baik_saluran_panjang_rb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='surveyor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saluran',
            name='surveyor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surveyor'),
        ),
    ]
