# Generated by Django 6.0.1 on 2026-02-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0054_detaillayananbangunan_kondisi_bangunan'),
    ]

    operations = [
        migrations.AddField(
            model_name='daerahirigasi',
            name='debit_awal',
            field=models.FloatField(default=0, verbose_name='Debit Awal Bendung (l/dt)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='debit_keluar',
            field=models.FloatField(default=0, verbose_name='Debit yang Diambil (l/dt)'),
        ),
    ]
