# Generated by Django 6.0.1 on 2026-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0055_daerahirigasi_debit_awal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='lebar_saluran',
            field=models.FloatField(default=0, verbose_name='Lebar Saluran (m)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='tinggi_saluran',
            field=models.FloatField(default=0, verbose_name='Tinggi Saluran (m)'),
        ),
    ]
