# Generated by Django 6.0.1 on 2026-02-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0056_detaillayananbangunan_lebar_saluran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_baik1',
            field=models.ImageField(blank=True, null=True, upload_to='survey/baik/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_baik2',
            field=models.ImageField(blank=True, null=True, upload_to='survey/baik/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_baik3',
            field=models.ImageField(blank=True, null=True, upload_to='survey/baik/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_baik4',
            field=models.ImageField(blank=True, null=True, upload_to='survey/baik/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_baik5',
            field=models.ImageField(blank=True, null=True, upload_to='survey/baik/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rb1',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rb/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rb2',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rb/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rb3',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rb/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rb4',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rb/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rb5',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rb/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rr1',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rr/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rr2',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rr/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rr3',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rr/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rr4',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rr/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_rr5',
            field=models.ImageField(blank=True, null=True, upload_to='survey/rr/'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='ket_baik',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='ket_rb',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='ket_rr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
