# Generated by Django 6.0.1 on 2026-02-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0057_detaillayananbangunan_foto_baik1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saluran',
            name='kode_aset_saluran',
            field=models.CharField(choices=[('S01', 'S01 - Saluran Primer'), ('S02', 'S02 - Saluran Sekunder'), ('S03', 'S03 - Saluran Suplesi'), ('S04', 'S04 - Saluran Muka'), ('S11', 'S11 - Saluran Pembuang'), ('S12', 'S12 - Saluran Gendong'), ('S13', 'S13 - Saluran Pengelak Banjir'), ('S15', 'S15 - Saluran Tersier'), ('S16', 'S16 - Saluran Kuarter'), ('S17', 'S17 - Saluran Pembuang (Tersier)'), ('P99', 'P99 - Saluran Lain-lain')], default='S01', max_length=50),
        ),
    ]
