# Generated by Django 6.0.1 on 2026-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0060_saluran_foto_baik_saluran_foto_rb_saluran_foto_rr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saluran',
            name='foto_baik',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumentasi Saluran Baik'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='foto_rb',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumentasi Saluran Rusak Berat'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='foto_rr',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumentasi Saluran Rusak Ringan'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='keterangan_baik',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Saluran Baik'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='keterangan_rb',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumentasi Saluran Rusak Berat'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='keterangan_rr',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumentasi Saluran Rusak Ringan'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='panjang_baik',
            field=models.FloatField(default=0, help_text='Total panjang kondisi Baik (m)', verbose_name='Panjang Saluran Kondisi Baik'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='panjang_rb',
            field=models.FloatField(default=0, help_text='Total panjang kondisi Rusak Berat (m)', verbose_name='Panjang Saluran Kondisi Rusak Berat'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='panjang_rr',
            field=models.FloatField(default=0, verbose_name='Panjang Saluran Kondisi Rusak Ringan'),
        ),
    ]
