# Generated by Django 6.0.1 on 2026-02-24 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0061_alter_saluran_foto_baik_alter_saluran_foto_rb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saluran',
            name='foto_bap',
            field=models.TextField(blank=True, null=True, verbose_name='Dokumentasi Belum Ada Pasangan'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='keterangan_bap',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Belum Ada Pasangan'),
        ),
        migrations.AddField(
            model_name='saluran',
            name='panjang_bap',
            field=models.FloatField(default=0, help_text='Total panjang kondisi belum ada pasangan (m)', verbose_name='Panjang Belum Ada Pasangan'),
        ),
        migrations.CreateModel(
            name='DetailSegmenSaluran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi', models.CharField(choices=[('BAIK', 'Baik'), ('RR', 'Rusak Ringan'), ('RB', 'Rusak Berat'), ('BAP', 'Belum Ada Pasangan')], max_length=10)),
                ('panjang', models.FloatField(default=0)),
                ('titik_awal', models.CharField(blank=True, max_length=255, null=True)),
                ('titik_akhir', models.CharField(blank=True, max_length=255, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('saluran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='apps.saluran')),
            ],
        ),
    ]
