# Generated by Django 6.0.1 on 2026-02-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0062_saluran_foto_bap_saluran_keterangan_bap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saluran',
            name='keterangan_bap',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Saluran Belum Ada Pasangan'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='keterangan_rb',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Saluran Rusak Berat'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='keterangan_rr',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan Saluran Rusak Ringan'),
        ),
    ]
