# Generated by Django 6.0.1 on 2026-03-03 04:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0063_alter_saluran_keterangan_bap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='is_saluran_berlanjut',
            field=models.BooleanField(default=True, verbose_name='Saluran Berlanjut (Ya/Tidak)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='jumlah_cabang_sekunder',
            field=models.IntegerField(default=0, verbose_name='Jumlah Cabang Sekunder'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='jumlah_cabang_tersier',
            field=models.IntegerField(default=0, verbose_name='Jumlah Cabang Tersier'),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='foto_aset',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey Admin'),
        ),
        migrations.AlterField(
            model_name='saluran',
            name='path_koordinat',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
    ]
