# Generated by Django 6.0.1 on 2026-03-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0064_detaillayananbangunan_is_saluran_berlanjut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='is_saluran_berlanjut',
            field=models.BooleanField(default=True, verbose_name='Saluran Berlanjut'),
        ),
        migrations.CreateModel(
            name='UnitPintuBangunan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pintu', models.IntegerField(default=1)),
                ('lebar_pintu', models.FloatField(default=0)),
                ('tinggi_pintu', models.FloatField(default=0)),
                ('kondisi', models.CharField(choices=[('BAIK', 'Baik'), ('RR', 'Rusak Ringan'), ('RB', 'Rusak Berat')], default='BAIK', max_length=10)),
                ('foto_pintu', models.ImageField(blank=True, null=True, upload_to='foto_pintu/')),
                ('detail_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_pintu', to='apps.detaillayananbangunan')),
                ('jenis_pintu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.jenispintu')),
            ],
        ),
    ]
