# Generated by Django 6.0.1 on 2026-03-05 06:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0066_alter_layerpendukung_warna_garis'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsegmensaluran',
            name='foto_admin',
            field=models.ImageField(blank=True, null=True, upload_to='segmen_saluran/', verbose_name='Upload Foto (Web)'),
        ),
        migrations.AddField(
            model_name='detailsegmensaluran',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Peta Segmen'),
        ),
    ]
