# Generated by Django 6.0.1 on 2026-03-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0067_detailsegmensaluran_foto_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='poligon_layanan',
            field=models.ForeignKey(blank=True, help_text='Pilih peta area yang dilayani oleh bangunan ini', limit_choices_to={'kategori': 'lahan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.layerpendukung', verbose_name='Poligon Area Layanan (Spasial)'),
        ),
    ]
