# Generated by Django 6.0.1 on 2026-04-01 09:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0068_detaillayananbangunan_poligon_layanan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsegmensaluran',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Peta Segmen'),
        ),
    ]
