# Generated by Django 6.0.1 on 2026-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0072_detailsegmensaluran_foto_admin_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_aset_2',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey Admin 2'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_aset_3',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey Admin 3'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_aset_4',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey Admin 4'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='foto_aset_5',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey Admin 5'),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='foto_aset',
            field=models.ImageField(blank=True, null=True, upload_to='foto_aset/bangunan/', verbose_name='Foto Survey Admin 1'),
        ),
    ]
