# Generated by Django 6.0.1 on 2026-04-03 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0073_detaillayananbangunan_foto_aset_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='jenis_saluran_kanan',
            field=models.CharField(choices=[('INDUK', 'Saluran Induk/Sekunder'), ('TERSIER', 'Saluran Tersier'), ('PENGURAS', 'Saluran Penguras'), ('MANUAL', 'Input Manual')], default='TERSIER', max_length=20, verbose_name='Jenis Saluran Kanan'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='jenis_saluran_kiri',
            field=models.CharField(choices=[('INDUK', 'Saluran Induk/Sekunder'), ('TERSIER', 'Saluran Tersier'), ('PENGURAS', 'Saluran Penguras'), ('MANUAL', 'Input Manual')], default='TERSIER', max_length=20, verbose_name='Jenis Saluran Kiri'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='jenis_saluran_tengah',
            field=models.CharField(choices=[('INDUK', 'Saluran Induk/Sekunder'), ('TERSIER', 'Saluran Tersier'), ('PENGURAS', 'Saluran Penguras'), ('MANUAL', 'Input Manual')], default='INDUK', max_length=20, verbose_name='Jenis Saluran Tengah'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='luas_kanan',
            field=models.FloatField(default=0, verbose_name='Luas Layanan Kanan (Ha)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='luas_kiri',
            field=models.FloatField(default=0, verbose_name='Luas Layanan Kiri (Ha)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='luas_tengah',
            field=models.FloatField(default=0, verbose_name='Luas Layanan Tengah (Ha)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='nomenklatur_kanan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenklatur Pintu Kanan'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='nomenklatur_kiri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenklatur Pintu Kiri'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='nomenklatur_tengah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nomenklatur Tengah'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='saluran_manual_kanan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Saluran Kanan (Manual)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='saluran_manual_kiri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Saluran Kiri (Manual)'),
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='saluran_manual_tengah',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nama Saluran Tengah (Manual)'),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='luas_areal',
            field=models.FloatField(default=0, verbose_name='Luas Areal Fungsional(Ha)'),
        ),
        migrations.AlterField(
            model_name='detaillayananbangunan',
            name='poligon_layanan',
            field=models.ForeignKey(blank=True, help_text='Pilih peta area yang dilayani oleh bangunan ini', limit_choices_to={'kategori': 'lahan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.layerpendukung', verbose_name='Poligon Area Layanan Fungsional'),
        ),
    ]
