# Generated by Django 6.0.1 on 2026-04-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0077_daerahirigasi_panjang_tersier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detaillayananbangunan',
            name='poligon_layanan',
        ),
        migrations.AddField(
            model_name='detaillayananbangunan',
            name='poligon_layanan',
            field=models.ManyToManyField(blank=True, help_text='Tahan tombol CTRL (Windows) atau CMD (Mac) saat mengklik untuk memilih lebih dari 1 poligon.', limit_choices_to={'kategori': 'lahan'}, to='apps.layerpendukung', verbose_name='Poligon Area Layanan Fungsional'),
        ),
    ]
