name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Icons & UI
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  
  # GPS & Location
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  latlong2: ^0.9.1
  
  # Networking & Maps
  http: ^1.1.0
  web_socket_channel: ^3.0.3
  flutter_map: ^6.1.0
  flutter_map_tile_caching: ^9.0.1
  
  # Database & Storage
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  
  # Media & Tools
  image_picker: ^1.0.4
  url_launcher: ^6.3.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_sirigasi.png"
  min_sdk_android: 21